### ISSUE TITLE
Не запускается jar файл

### ISSUE THREAD

**Issue by ewan132** [ewan132/QAATDiplom#2]
При запуске команды возникает ошибка:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
 

```

```
om.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.18.jar!/:8.0.18]       
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-java-8.0.18.jar!/:8.0.18]
 
```
Ранее джарник открывался (17.10.2024) до настройки контейнера

Запуск джарника осуществляется командой:
java -jar ./artifacts/aqa-shop.jar 
Так же пробовал запустить командой
 java -jar ./artifacts/aqa-shop.jar --server.port=8080

![image](https://github.com/user-attachments/assets/6278a517-b646-4a5d-b426-2c0c135a7dd5)

**Comment by ewan132** [comment]
Необходимо добавить подключение к БД 
docker container run -d -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=app -e MYSQL_USER=app -e MYSQL_PASSWORD=pass mysql
